// <auto-generated />
using LaLiga.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaLiga.Migrations
{
    [DbContext(typeof(LaligaDbContext))]
    [Migration("20260306114241_Initials")]
    partial class Initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaLiga.Models.Match", b =>
                {
                    b.Property<string>("MatchID")
                        .HasColumnType("char(6)");

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeamID")
                        .HasColumnType("char(3)");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeamID")
                        .HasColumnType("char(3)");

                    b.HasKey("MatchID");

                    b.HasIndex("AwayTeamID");

                    b.HasIndex("HomeTeamID");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            MatchID = "RMAFCB",
                            AwayScore = 1,
                            AwayTeamID = "FCB",
                            HomeScore = 2,
                            HomeTeamID = "RMA"
                        },
                        new
                        {
                            MatchID = "ATMFCB",
                            AwayScore = 0,
                            AwayTeamID = "FCB",
                            HomeScore = 4,
                            HomeTeamID = "ATM"
                        });
                });

            modelBuilder.Entity("LaLiga.Models.Standings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("GoalDifference")
                        .HasColumnType("int");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("Played")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Standings");
                });

            modelBuilder.Entity("LaLiga.Team", b =>
                {
                    b.Property<string>("TeamID")
                        .HasColumnType("char(3)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadium")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamID");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamID = "RMA",
                            City = "Madrid",
                            Name = "Real Madrid",
                            Stadium = "Esatdio Santiago Bernabeu"
                        },
                        new
                        {
                            TeamID = "FCB",
                            City = "Barcelona",
                            Name = "FC Barcelona",
                            Stadium = "Spotify Camp Nou"
                        },
                        new
                        {
                            TeamID = "ATM",
                            City = "Madrid",
                            Name = "Atletico Madrid",
                            Stadium = "Wanda Metropolitano"
                        });
                });

            modelBuilder.Entity("LaLiga.Models.Match", b =>
                {
                    b.HasOne("LaLiga.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LaLiga.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });
#pragma warning restore 612, 618
        }
    }
}
